    - name:  Update the apt package index
      shell: apt-get update
      become: yes
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: ../files/nginx/static.cfg
        dest: /etc/nginx/sites-available/static.cfg
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/static.cfg
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: copy the content of the web site
      copy:
        src: ../files/nginx/static/
        dest: /var/www/html
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes