- hosts: web
  tasks:
    - name: stop nginx
      service:
        name: nginx
        state: stopped
      become: yes
    - name: ensure nginx is not installed
      apt: name=nginx state=absent
      become: yes